### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by harikt** [atlasphp/Atlas.Orm#27]
Hi Paul, 

I came across a strange issue in relationship. Was trying to write a unit test, but reading  https://github.com/atlasphp/Atlas.Orm#relationships I got a bit confused so thought of discussing the same.

We have an `articles` table and `users` table.
## Articles Table

| id | user_id | title | body |
| --- | --- | --- | --- |
| 1 | 1 | something | something |
| 2 | 1 | another | another |
## Users Table

| id | name |
| --- | --- |
| 1 | James |
| 2 | Bond |

The mapper was defined as 

``` php
class ArticleMapper extends \Atlas\Orm\Mapper\AbstractMapper
{
    protected function setRelated()
    {
        $this->manyToOne('user', UserMapper::CLASS);
        //    ->on([
        //        'user_id' => 'id'
        //    ]);
    }
}

class UserMapper extends \Atlas\Orm\Mapper\AbstractMapper
{
    protected function setRelated()
    {
        $this->oneToMany('articles', ArticleMapper::CLASS); 
        // added on later
    }
}
```

Now when you fetch article id 2 it returns `Bond` as user, but it should return James instead.

```
$record = $atlas->fetchRecord(ArticleMapper::CLASS, 2, ['user']);
echo $record->user->name;
```

When we add `on` it works as expected. I noticed when we change article id to 3, it tries to fetch user with id 3. Is that expected ? That is where I got confused with the docs https://github.com/atlasphp/Atlas.Orm#relationships

> By default, in all relationships except many-to-one, the relationship will take the primary key column(s) in the native table, and map to those same column names in the foreign table. In the case of many-to-one, it is the reverse; that is, the relationship will take the primary key column(s) in the foreign table, and map to those same column names in the native table.

Thank you

**Comment by akDeveloper** [comment]
In your `UserMapper` class i see that you define `oneToMany` as 
`$this->oneToMany('user', ArticleMapper::CLASS);`
Is this a typo? 
I think it should be like this
`$this->oneToMany('articles', ArticleMapper::CLASS);`

**Comment by harikt** [comment]
@akDeveloper yes that was a typo in what I have written here not in source code.

Have updated the comment.

Thank you.

**Comment by jakejohns** [comment]
I _think_ the issue is that it's mapping `articles.id` to `users.id`, but you want it to map `articles.user_id` to `users.id`

Docs say:

> [...] **same column names** in the foreign table.
> [...] map to those **same column names** in the native table.

So you gotta use the `on` method like you said if you want to use the terse `id` form for primary keys, 

**or** you can change the db structure to use the same explicit column names if you want to use the "auto mapping" .... so like this:

### article table

| article_id | user_id | title | body |
| --- | --- | --- | --- |
| 1 | 1 | something | something |
| 2 | 1 | another | another |

### user table

| user_id | name |
| --- | --- |
| 1 | James |
| 2 | Bond |

So `user_id` is the name of the column in both tables.

**Comment by harikt** [comment]
@jakejohns yes. After your post, I re-read the docs once again today and sounds right.

Thank you.
