### ISSUE TITLE
ManyToMany and Fetching Relateds

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#54]
This is more of a question/confirmation of behaviour than an issue. 
Consider the ubiquitous blog example of a `posts` table having many `tags` through a `taggings` association table. With the relationships defined, if you want to fetch the tags for a given post, you have to explicitly pass both the `taggings` relationship and the `tags` relationship to the fetch method. Is this correct? My original assumption was that I would only have to pass the `tags` relationship and atlas would perform the join magic based on the relationship definition. This did not seem to work in my testing. Can you confirm that the association table must also be included? Or do I have something configured poorly?

For example:

```
$post = $atlas->fetchRecord(
    Post::class, 
    2, 
    [
        'taggings', // Is this necessary?
        'tags'
    ]
);
```

**Comment by pmjones** [comment]
> Can you confirm that the association table must also be included?

CAN CONFIRM ;-)

More seriously: yes, you do have to "manually" call `with()`on the intervening association relationship. This is mostly because I'd like the operation of the relationships to transparent and intentional; that is, if you're getting "tag" you as the developer should know and intend that it happens via "taggings."

This should be documented more explicitly.

Additionally, maybe I should relax the explicitness a little and see if I can load the "taggings" when you call for "tags".

**Comment by jelofson** [comment]
Thanks @pmjones . That makes sense. I have no problem with calling the association relationship explicitly, though this is the first I have seen an ORM require it and therefore was confused. As long as it's documented, that's fine with me.
