### ISSUE TITLE
[Docs] Missing database model

### ISSUE THREAD

**Issue by froschdesign** [atlasphp/Atlas.Orm#78]
### Problem

In the documentation is used the database with name `testdb`. In many description these tables are used:

* `threads`
* `author`
* `summary`
* `replies`
* `taggings`
* `tags`
* `comments`

But nowhere we can find the database model or any other introduction to this example database.

### Suggestion

Add a graphical database model to illustrate the tables, columns and relations. (Optimal would we be the SVG format.)

**Comment by andrewshell** [comment]
I'd be happy to put this together, including a separate repo with a sample app.  It will require some tweaking because currently, the examples are mostly standalone to illustrate the specific feature.  That's why in some instances you'll see references that the `threads` primary key is `id` and other times it's implied that it's `thread_id`.

@pmjones How would you like me to handle ambiguities like the id example above? I can just use my judgment then have you review when I'm done. Or would you like to hash these things out before I get too far?

**Comment by harikt** [comment]
This is what I think, the examples model code is already in the tests ( https://github.com/atlasphp/Atlas.Orm/tree/2.x/tests/DataSource ) .

Probably those examples can be moved to a separate repo and then the package can be included on require-dev . This helps to reduce the complexity of changes happening on tests and on examples.

Regarding documentation, yes it probably need to be improved. May be as @froschdesign mentioned good with pictures or some table structures may help.

**Comment by pmjones** [comment]
> Probably those examples can be moved to a separate repo and then the package can be included on require-dev 

Per @harikt's suggestion, for the upcoming new round of Atlas releases, I have created an Atlas.Testing package: https://github.com/atlasphp/Atlas.Testing

@froschdesign if you (or anyone else!) would like to put together some docs within that new package, I'd be very happy to review PRs.

Thanks all!
