### ISSUE TITLE
Missing get PDO connection from Atlas ORM

### ISSUE THREAD

**Issue by gugglegum** [atlasphp/Atlas.Orm#99]
I have an instance of `Atlas\Orm\Atlas` object and I pass this object to constructors of different classes which need to do something with database. But sometimes these classes need to execute raw SQL query because it's too complex for Atlas ORM or not supported syntax. So I need to pass into costructor both Atlas ORM object and PDO object. This is not convenient.

It will be just excellent if Atlas ORM will be able to give its `PDO` (or `Atlas\Pdo\Connection`) object for some low-level queries. Currently access to PDO from Atlas is prohibited.

**Comment by pmjones** [comment]
It should be possible to "reach down" through the layers to get to the underlying PDO instance:

`$pdo = $atlas->mapper(Mapper::class)->getTable()->getReadConnection()->getPdo();`

(Or `getWriteConnection()`.)

This is ugly, though I opine it ought to be, since it breaks at least two rules of good practice.

Is that solution sufficient for your purposes? If not, let me know what you might find more suitable.

(I note now that the functionality is not documented, and probably should be -- if you feel like submitting a PR for that, I can review and merge so you get credit for it; otherwise, I'll put it on my backlog.)

**Comment by gugglegum** [comment]
Yes, this solution is sufficient. I just could not find it in the documentation and by code analysis. The only inconvenience in this solution is that I need to put some concrete mapper class here. It may be any class since all mapper classes uses the same DB connection but this make code not intuitive and messy. For example, I need PDO object to call stored procedure. Which mapper class should I select? It would be better if I could make something like:

`$pdo = $atlas->getReadConnection()->getPdo();`
